stages:
  - test
  - docker

test:
  stage: test
  image: golang
  script:
    - go test
  rules:
    # pouze pokud je to push
    - if: $CI_PIPELINE_SOURCE == "push"

build:
  stage: test
  image: golang
  script:
    - CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -o ./server ./server.go
  rules:
    # pouze pokud je to push
    - if: $CI_PIPELINE_SOURCE == "push"



docker-test-build:
  stage: docker
  image: docker:24.0.7-dind
  script:
  # pro zkousku, jestli projde docker build
    - docker build .
  rules:
    # pouze pokud je to push nebo se zmeni Dockerfile
    - if: $CI_PIPELINE_SOURCE == "push"
    - changes:
        - Dockerfile

docker:
  stage: docker
  image: docker:24.0.7-dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/httpserver:$CI_COMMIT_TAG .
    - docker login -u $SERVICE_USER -p $SERVICE_USER_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/httpserver:$CI_COMMIT_TAG
  only:
    - tags

